### ISSUE TITLE
Flutter Web and openid?

### ISSUE THREAD

**Issue by Jeremywhiteley** [teranetsrl/oauth2_client#1]
Any plans to make this work with open ID connect and flutter web?

**Comment by okrad** [comment]
Hi @Jeremywhiteley, OpenID Connect support is definitely on the roadmap. 
As for flutter web, we are currently thinking about it. It could be split in a second package since we would need a dedicated set of dependencies.

**Comment by Jeremywhiteley** [comment]
We really need a OpenID Connect solution that works with both Web and Mobile.  So we can have a one code base.  Similar to what they did with Firebase Auth.   So far I haven't found one.  I want to get it work with Azure AD B2C.

**Comment by teranetsrl** [comment]
Your insight is much appreciated and I can understand your requirements. Will surely take into consideration porting the library to the web platform.
