### ISSUE TITLE
Oauth2 Refresh tokens

### ISSUE THREAD

**Issue by jainilparikh** [teranetsrl/oauth2_client#10]
Hi ,
Once I have created my custom OAuth2Client class as shown 
```
import 'package:oauth2_client/oauth2_client.dart';
import 'package:meta/meta.dart';

class CustomClient extends OAuth2Client {
  MyOAuth2Client({@required String redirectUri, @required String customUriScheme}): super(
    authorizeUrl: 'https://...', //Your service's authorization url
    tokenUrl: 'https://...', //Your service access token url
    redirectUri: redirectUri,
    customUriScheme: customUriScheme
  );
}
```
Can you tell me how do I Check if my token is expired or not? 
I fetch the token using 

```
`OAuth2Client client = CustomClient(
      redirectUri: URL',
      customUriScheme: 'com.example.Companyname');

  OAuth2Helper oauth2Helper = OAuth2Helper(client,
      grantType:
          OAuth2Helper.CLIENT_CREDENTIALS, //default value, can be omitted
      clientId: '',
      clientSecret: '',
      scopes: ['']);            //       Assume these values to be filled...

  oauth2Helper.fetchToken().then((val) {
    print(val); // My token 
  });`
```

My approach would be to check for 401 response from the API I am calling
Is there any predefined method that I can implement?

**Comment by hite77** [comment]
From the readme, there is an example where you retrieve the token, and then call a method on the token to check if it has expired...

//Import the client you need (see later for available clients)...
import 'myclient.dart'; //Not an actual client!
import 'package:oauth2_client/access_token.dart';

...

//Instantiate the client
client = MyClient(...);

//Request a token using the Authorization Code flow...
AccessToken token = client.getTokenWithAuthCodeFlow(
	clientId: 'your_client_id',
	scopes: ['scope1', 'scope2', ...]
);

//Request a token using the Client Credentials flow...
AccessToken token = client.getTokenWithClientCredentialsFlow(
	clientId: 'XXX', //Your client id
	clientSecret: 'XXX', //Your client secret
	scopes: ['scope1', 'scope2', ...] //Optional
);

//Or, if you already have a token, check if it is expired and in case refresh it...
if(token.isExpired()) {
	token = client.refreshToken(token.refreshToken);
}

**Comment by okrad** [comment]
Hi @jainilparikh, you don't need to check for token expiration if you are using the helper class... That's exactly the helper's job: to detect expired tokens and in case fetch new ones and store them in the secure storage.

Anyway, if for your particular use case you need to check for token expiration, you can directly use the client class, as @hite77 suggested, instead of the helper.

Bear in mind that the token can be invalidated on the server before its expected expiration, so you'll need to check for this particular condition other than using the `isExpired` method alone...

For example, first fetch the access token:

```
OAuth2Client client = GitHubOAuth2Client(
    //Corresponds to the android:scheme attribute
    customUriScheme: 'my.app',
    //The scheme must match the customUriScheme parameter!
    redirectUri: 'my.app://oauth2redirect'
);

//Require an Access Token with the Authorization Code grant
AccessTokenResponse tknResp = await client.getTokenWithAuthCodeFlow(
    clientId: 'myclientid',
    clientSecret: 'myclientsecret',
    scopes: ['repo']);
```

Then, whenever you need to perform a request to the API server...
```
//Check if token is expired
if(tknResp.isExpired()) {
  tknResp = await client.refreshToken(tknResp.refreshToken);
}

if(tknResp.isValid()) {
  //From now on you can perform authenticated HTTP requests
  httpClient = http.Client();
  http.Response resp = await httpClient.get('https://api.github.com/user/repos',
    headers: {'Authorization': 'Bearer ' + tknResp.accessToken});
  //The request to the service didn't succeed...
  //We must refresh the token (or generate a new one...)
  if(resp.statusCode == 401) {
    tknResp = await client.refreshToken(tknResp.refreshToken);    
    //Perform another request to the server with the new access token
    http.Response resp = await httpClient.get('https://api.github.com/user/repos',
        headers: {'Authorization': 'Bearer ' + tknResp.accessToken});
  }
}
```
```

**Comment by jainilparikh** [comment]
Hi Thanks @okrad and @hite77 your replies helped me implement the plugin in my project.


I have a doubt.

When I was   going through your oauth2_helper.dart i found tknResp.isValid() on line 91. Could you tell me exactly how you are checking the validity of the token? and how the isValid() function works?

**Comment by okrad** [comment]
Hi @jainilparikh , the `isValid ` method checks if the access token response has a valid HTTP status (200) and if it doesn't contain an "error" field.

**Comment by jainilparikh** [comment]
Thanks @okrad.

**Comment by eggman87** [comment]
@okrad what would you recommend for API where authentication is optional? Is there a way to check if a token is currently stored through the library API? 

the flow would be, if user is not authenticated -> call api without helper, if authenticated use helper (this would strictly be for auth optional apis). Maybe we can add a param to the request methods to specify if auth is required or not so the helper only tries to reauth user if it is required.
