### ISSUE TITLE
Authorise request has broken scope parameter

### ISSUE THREAD

**Issue by AndrewStickler** [teranetsrl/oauth2_client#100]
Commit [e503516] seems to have broken the authorize request, as it has changed the scope separator from a space to a plus character. Can this be undone please, as oauth is now broken with V2.2.4.

Thanks,
Andrew

**Comment by okrad** [comment]
Hi @AndrewStickler, I restored the scope separator and published version 2.2.5, can you check it out?

**Comment by AndrewStickler** [comment]
Yes that's fixed now, thanks.
