### ISSUE TITLE
preferEphemeral flag isn't exposed.

### ISSUE THREAD

**Issue by AndrewStickler** [teranetsrl/oauth2_client#101]
The fix for issue #96 doesn't appear to provide a way to configure the new ephemeral flag from either the OAuth2Client class or the OAUth2Client.getTokenWithAuthCodeFlow() method, so there is no way to actually make use of it. 
Shouldn't preferEphemeral be passed down from higher up the call stack?

**Comment by okrad** [comment]
You are right, that part was missing!
I just published a new version, now you can set the flag directly in the client or in the helper. For example:

```dart
var client = OAuth2Client(...);
client.getTokenWithAuthCodeFlow(
   ...,
   webAuthOpts: {'preferEphemeral': true}
);

//Or, using the helper...
var hlp = OAuth2Helper(client, 
   ..., 
   webAuthOpts: {'preferEphemeral': true}):
hlp.fetchToken();
```

**Comment by AndrewStickler** [comment]
That works for me now - thank you very much.

**Comment by Cilenco** [comment]
I feel like this is pretty hard to find, had to do some research also on the dependency repo. You might want to consider adding this to the default example for Android :)
