### ISSUE TITLE
Supporting Flutter desktop?

### ISSUE THREAD

**Issue by domesticmouse** [teranetsrl/oauth2_client#12]
I'd like to add Flutter for desktop support to oauth2_client. I suspect this will mean turning `oauth2_client` into a [federated plugin](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#federated-plugins) so we can add support for macOS. 

Thoughts?

**Comment by okrad** [comment]
Hi @domesticmouse, that would be great, as it would simplify porting the library to the web platform too (which is something I get requested often).

I must admit I didn't even know federated plugins existed, but I definetely like the idea of defining an interface and to be able to simply extend it to implement platform specific packages.

I need to understand how to best refactor the code... I think I'll create a new branch in the next days to start experimenting ... Do you have any advices on how/where to start?

**Comment by domesticmouse** [comment]
At this point I don't have anything specific to add over and above [How To Write a Flutter Web Plugin: Part 2](https://medium.com/flutter/how-to-write-a-flutter-web-plugin-part-2-afdddb69ece6), but I'll spend a chunk of this week digging into your plugin and playing about. When you have a branch up hopefully I'll have some concrete PRs to submit. =)

**Comment by domesticmouse** [comment]
Actually, digging into this further, it looks like your [`flutter_web_auth`](https://pub.dev/packages/flutter_web_auth) already handles macOS. I'd also suggest that handling Flutter for web should probably also be handled directly by `flutter_web_auth`.

During my investigations, I put together https://github.com/teranetsrl/oauth2_client/pull/14 primarily as a cleanup. Not required, but probably nice to have. hth!

**Comment by okrad** [comment]
Thank you for the PR!

As for desktop support, I wasn't aware that the latest flutter_web_auth update already handles macOS...

What about the other dependency, [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) that is used by the helper class to securely store the access tokens? It doesn't seem to support flutter desktop at all...

**Comment by domesticmouse** [comment]
Yeah, it really doesn't. For the short term I'm utilising [`oauth2`](https://pub.dev/packages/oauth2) as I got lost while trying to figure out how to get `flutter_secure_storage` to play nicely with desktop.
