### ISSUE TITLE
How to  clear the cookie of the webview?

### ISSUE THREAD

**Issue by westlinkin** [teranetsrl/oauth2_client#125]
after delete the app, re-install the app, click the login button, I should be able to type the username and password in, instead,  I immediately see the screen to "allow / grant" my app's access.

We should see a brand new webview every time we start the oauth process.

Thanks in advance

**Comment by Mubaola23** [comment]
I'm also facing the same issue

**Comment by okrad** [comment]
Hi @westlinkin, are you in iOS or Android?
If on iOS, can you try to instantiate the helper with the "preferEphemeral" param set to false?

For example:
```dart
var hlp = OAuth2Helper(client,
 clientId: ...,
 scopes: [...],
 webAuthOpts: {'preferEphemeral': false}
);
```

**Comment by westlinkin** [comment]
@okrad Thanks. This happens both on Android and iOS.

I used the [flutter_webview](https://pub.dev/packages/webview_flutter) instead. Just implement the `navigationDelegate` function. If the nativigation.url contains the token, exist the webview and continue the login logic.

**Comment by okrad** [comment]
@westlinkin, I'm glad you solved issue! 

Just a warning: using a webview [is discouraged](https://www.oauth.com/oauth2-servers/oauth-native-apps/use-system-browser/) in an OAuth 2 flow for security concerns.

**Comment by westlinkin** [comment]
@okrad Thanks for the heads up!
