### ISSUE TITLE
Open and authorize through an installed app (vs browser)?

### ISSUE THREAD

**Issue by asmith26** [teranetsrl/oauth2_client#127]
Hi there,

I'm using this (fantastic) lib to connect to a user's Dropbox. When authorizing the connection, my app currently opens a browser - is it possible to connect to a pre-installed (and probably already logged into) app?

```dart
class DropboxOAuth2Client extends OAuth2Client {
  DropboxOAuth2Client(
      {required String redirectUri, required String customUriScheme})
      : super(
            authorizeUrl: 'https://www.dropbox.com/oauth2/authorize',  // possibly need to change this to open the Dropbox app instead?
            tokenUrl: 'https://api.dropboxapi.com/oauth2/token',
            redirectUri: redirectUri,
            customUriScheme: customUriScheme);
}
```

Many thanks for any help, and for this amazing lib! :)

**Comment by okrad** [comment]
Hi @asmith26, I'm sorry, no... 
I can't even imagine how a process like that could work. The Dropbox app probably uses the Dropbox OAuth service to retrieve a token, and I doubt it provides a way to access the token from any other app, even just for security reasons...

**Comment by asmith26** [comment]
Many thanks for the response and info @okrad, that makes sense.
