### ISSUE TITLE
Unable to upload a binary file (Dropbox)

### ISSUE THREAD

**Issue by asmith26** [teranetsrl/oauth2_client#129]
Hi there, I'm trying to upload a binary file to Dropbox using this lib. Following https://dropbox.github.io/dropbox-api-v2-explorer/#files_upload, my code is:

```dart
http.Response resp =
    await helper.post('https://content.dropboxapi.com/2/files/upload',
        headers: {
          'Content-Type': 'application/octet-stream',
          'Dropbox-API-Arg': '{"path": "/file", "mode": "overwrite"}',
        },
    body: "--data-binary @\'/my/binary/file\'",
);
```

`file` gets uploaded, but unfortunately this only contains the text `--data-binary @'/my/binary/file'` (i.e. not the actual file).

**Am I missing something/doing something incorrectly?** (Mentioning @alensugimoto having [possibly](https://github.com/teranetsrl/oauth2_client/issues/91#issuecomment-895480236) worked with this lib + Dropbox).

Many thanks for any help, and for this amazing lib! :)

**Comment by alensugimoto** [comment]
Hello! Try sending the binary data directly in the body. I think this should help: https://stackoverflow.com/a/59181327/17160612.

**Comment by asmith26** [comment]
Thank you so much for the tip @alensugimoto, I got this to work:

```dart
      // Create byte data
      final file = File('/my/binary/file');
      Uint8List data = await file.readAsBytes();

      http.Response resp =
          await helper.post('https://content.dropboxapi.com/2/files/upload',
              headers: {
                'Content-Type': 'application/octet-stream',
                'Dropbox-API-Arg': '{"path": "/file", "mode": "overwrite"}',
              },
              body: data);
```

**Comment by alensugimoto** [comment]
Glad it helped!
