### ISSUE TITLE
Add client_id to refreshToken Request

### ISSUE THREAD

**Issue by yannickscholz** [teranetsrl/oauth2_client#13]
Hey, can you add a client_id parameter to the refreshToken method or a parameter List that can extend the body? I get an error form our AuthProvider. Thanks.

**Comment by eyeoftime** [comment]
I'd like to second this. I'm trying to integrate to an OAuth provider that requires the client_id to be sent along with the refresh_token in order to obtain a new access_token

**Comment by okrad** [comment]
Hi, you are right, the specs state that the client_id and the client_secret should be sent alongside the refresh token request, if they were needed for the access token flow used in the first place.

I'm going to add them in the next release.
