### ISSUE TITLE
A client for Twitter?

### ISSUE THREAD

**Issue by myConsciousness** [teranetsrl/oauth2_client#131]
Hi amazing developers, 

I was trying to create a library to authenticate with Twitter's OAuth 2.0 PKCE and luckily I found this library. At first glance this seems applicable to Twitter OAuth2, but is there a plan to implement this for Twitter?

Thank you.

**Comment by myConsciousness** [comment]
If that implementation is feasible with this library, I will create a pull request when I have time :)

**Comment by okrad** [comment]
Hi @myConsciousness, something like the following should do the job:

```dart
import 'package:oauth2_client/oauth2_client.dart';

class TwitterOAuth2Client extends OAuth2Client {
  TwitterOAuth2Client(
      {required String redirectUri, required String customUriScheme})
      : super(
            authorizeUrl: 'https://twitter.com/i/oauth2/authorize',
            tokenUrl: 'https://api.twitter.com/2/oauth2/token',
            revokeUrl: 'https://api.twitter.com/oauth2/invalidate_token',
            redirectUri: redirectUri,
            customUriScheme: customUriScheme);
}
```

...Provided that the endpoint urls are correct, I found different variants...

If you are able to test it, I would gladly add it to the package!

**Comment by myConsciousness** [comment]
Hi @okrad ,

I am finally working on this issue. Can this library be tested in a local environment only? I have tried several times to check the operation with Flutter for Web in my local environment, but the Stream process that is executed with the following redirect does not start.

```dart
class BrowserWebAuth implements BaseWebAuth {
  @override
  Future<String> authenticate(
      {required String callbackUrlScheme,
      required String url,
      required String redirectUrl,
      Map<String, dynamic>? opts}) async {
    // ignore: unsafe_html
    final popupLogin = html.window.open(
        url,
        'oauth2_client::authenticateWindow',
        'menubar=no, status=no, scrollbars=no, menubar=no, width=1000, height=500');

    //! Here
    var messageEvt = await html.window.onMessage
        .firstWhere((evt) => evt.origin == Uri.parse(redirectUrl).origin);

    popupLogin.close();

    return messageEvt.data;
  }
}
```

Thank you.

**Comment by myConsciousness** [comment]
At least I could open this as a popup, but nothing happens from there after authorize the redirect. 

In the standard authorization flow, the authorization code is exchanged after the authorize button is pressed, but this does not occur and the popup is not closed in the first place, causing a redirect in the popup.

I was going to test on localhost, but am I doing something wrong?

<img width="701" alt="スクリーンショット 2022-06-02 9 11 02" src="https://user-images.githubusercontent.com/13072231/171521617-895ea2a9-ad61-46c9-9e1a-10e3e47d237b.png">

**Comment by myConsciousness** [comment]
Hi @okrad ,

I finally got this working, but after much consideration, I feel that it would be better to develop the implementation for Twitter as a separate package, so I will not merge this implementation into this package!

I would like to provide a scope specification in Enum, etc., so I felt it would be better to proceed with development in a separate package. 

Thank you anyway!

**Comment by novas1r1** [comment]
Hey @myConsciousness,
how did you get it working? I have the same issue, the page comes up, but its loading endlessly after clicking on authorize. Would be really happy if you could tell me how you fixed this.

Best regards and thanks in advance!
