### ISSUE TITLE
`Error: The getter 'IOSAccessibility' isn't defined for the class 'SecureStorage'.`

### ISSUE THREAD

**Issue by asmith26** [teranetsrl/oauth2_client#135]
I'm hoping to upgrade my android SDK version to v33 (i.e. [this number](https://github.com/okrad/oauth2_client_test/blob/31235034cb247e364a1701716373bb4ca3080977/android/app/build.gradle#L29)), but when I do this I get the following error:

```dart
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/oauth2_client-2.4.1/lib/src/secure_storage.dart:21:47: Error: The getter 'IOSAccessibility' isn't defined for the class 'SecureStorage'.
 - 'SecureStorage' is from 'package:oauth2_client/src/secure_storage.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/oauth2_client-2.4.1/lib/src/secure_storage.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'IOSAccessibility'.
    final options = IOSOptions(accessibility: IOSAccessibility.first
```

## Possible Fix

It would appear this `IOSAccessibility` name has changed to `KeychainAccessibility`: https://github.com/mogol/flutter_secure_storage/pull/405

**Comment by herrmayr** [comment]
I also cannot build my app anymore on iOS and the log seems to point to this issue as well:

> ../../../flutter/.pub-cache/hosted/pub.dartlang.org/oauth2_client-2.4.1/lib/src/secure_storage.dart:15:47: Error: The getter 'IOSAccessibility' isn't defined for the class 'SecureStorage'.
>  'SecureStorage' is from 'package:oauth2_client/src/secure_storage.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/oauth2_client-2.4.1/lib/src/secure_storage.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'IOSAccessibility'.
>     final options = IOSOptions(accessibility: IOSAccessibility.first_unlock);
> Failed to package /Users/......
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by felix-barz-brickmakers** [comment]
Adding the following to your pubspec.yaml temporarily overrides the flutter_secure_storage to use the last compatible version until this issue gets fixed:

```pubspec.yaml
dependency_overrides:
  flutter_secure_storage: 5.0.2 # https://github.com/teranetsrl/oauth2_client/issues/135
```

**Comment by okrad** [comment]
Thank you @asmith26, let me know if the latest release solves the problem!

**Comment by asmith26** [comment]
> Thank you @asmith26, let me know if the latest release solves the problem!

Seems to be working well for me so far thanks :)
