### ISSUE TITLE
Update `flutter_web_auth` to `flutter_web_auth_2`?

### ISSUE THREAD

**Issue by ThexXTURBOXx** [teranetsrl/oauth2_client#137]
I finally took the initiative and updated `flutter_web_auth` for proper Flutter 3 support (using noga-dev's changes) and some more stuff!
The new package is available here: https://pub.dev/packages/flutter_web_auth_2
Since I think that my updated package is only compatible with Flutter 3+, it might be worth noting this as a breaking change and providing a new major version number for the users

Edit: I forgot to mention that migrating is pretty easy: https://pub.dev/packages/flutter_web_auth_2#upgrading-from-flutter_web_auth

**Comment by PiotrMitkowski** [comment]
@okrad if you have nothing against, I can take care of the migration. There's no contact with the author (which you can see e.g. under this PR, that was made to support Flutter 3: https://github.com/LinusU/flutter_web_auth/pull/118). Thanks!

**Comment by okrad** [comment]
@ThexXTURBOXx, @PiotrMitkowski sorry for the late reply, I'm quite busy ATM...

I too am under the impression that flutter_web_auth is in a stale state, and was already looking for other viable solutions. If you are willing to carry on the fork it would be great! There are definitely a couple of PRs that I'd like to see merged, starting with Linux support...

@PiotrMitkowski, I'd gladly accept a PR for the migration. Can you update the README too?

Thank you!

**Comment by ThexXTURBOXx** [comment]
@okrad Yes, I am trying to keep my fork as up-to-date as possible. Also, i was already merging many PRs that added Windows support, better support for Android, MacOS and iOS and so on.
There is also a big restructure going on (which does not break packages, but refactors the inner workings of the package).
If @PiotrMitkowski wants to do this, he should just go ahead! If he does not do it within the next few days, I will just do it myself then :)

**Comment by PiotrMitkowski** [comment]
@okrad @ThexXTURBOXx No problem, I'll land the PR soon.

**Comment by ThexXTURBOXx** [comment]
This is done :)
