### ISSUE TITLE
[Question] Need help with GitHubOAuth2Client

### ISSUE THREAD

**Issue by AntiqPeace** [teranetsrl/oauth2_client#15]
Hi, this is more of a help question rather than an issue. I didn't know where to ask.Sorry for that...

I am completely new to this OAuth world. I tried to implement GitHub OAuth flow as described in Readme of this repo.

I also created an OAuth App at github.com/settings/developers. But, I am not sure what to put in 'Authorisation Callback URL'. Do I need to put a valid website URL? If yes, I tried putting `example.com`. And when I log-in, it just redirects to the example.com. 

My question is, how to get the control back to our app when user logs-in to GitHub?

If I have to put a valid website URL in that (Authorisation callback URL), then what response do I need to send from my website URL, so that it gets back to my app??

Thanks.

**Comment by okrad** [comment]
Hi @AntiqPeace,  in the first step of the "Authorization Code" grant, the client requests an "Authorization Token". After the user grants access to the resource, the server redirects the client to the "redirect uri" (i.e. the "callback url") sending the Authorization Token as a parameter.

The client must therefore be able to intercept the redirection... Normally, urls with the http(s) scheme are handled by the system browser, but in a mobile app you want your app to be the one who intercepts and handles the redirect, so you must use a "custom" url scheme. This can be almost anything you want (as well as the rest of the callback url), e.g. "my.app"... 
You could for example define a callback url like "my.app://oauth2redirect".

If you are developing for Android, don't forget to modify the `manifest.xml` file adding an `intent-filter` for the custom scheme (as indicated in the README), or else your app won't be able to intercept the redirect url.

If you need a broader (yet simplified) introduction to OAuth2, you can [read my article](https://dev.to/okrad/oauth2client-implement-oauth2-clients-with-flutter-4jjll) on the subject.

**Comment by AntiqPeace** [comment]
@okrad thanks for your help. It worked...
You may close this issue now.
