### ISSUE TITLE
Query param error

### ISSUE THREAD

**Issue by juanagu** [teranetsrl/oauth2_client#151]
Hello, I'm trying to use the next params

```
const params = {
      'response_type': 'token',
      'display': 'page',
      'extras': {'setup':{'channel':'IG_API_ONBOARDING'}},
    };
```

The function [params2qs](https://github.com/teranetsrl/oauth2_client/blob/4d80697a42e785053af37d6cb5a276cdc2dc76cd/lib/src/oauth2_utils.dart#L23) should check if the value is String before to do a `v.trim()`

**Comment by juanagu** [comment]
Possible solution:

```
params.forEach((k, v) {
      String val;
      if (v is List) {
        val = Uri.encodeComponent(v.map((p) => p.trim()).join(' '));
      } else if (v is Map) {
        val = jsonEncode(v);
      } else {
        val = v.toString().trim();
      }
      qsList.add(k + '=' + val);
});
```

**Comment by okrad** [comment]
@juanagu thank you, you are right, I will add the patch in the next release
