### ISSUE TITLE
Google doesn't return refresh_token after first expire

### ISSUE THREAD

**Issue by iofjuupasli** [teranetsrl/oauth2_client#16]
https://github.com/teranetsrl/oauth2_client/blob/c834a30bb16b8ca5fec52b68b9ecde4aa861b2df/lib/src/token_storage.dart#L37-L50

Steps:
1. With Google OAuth 2.0 Mobile
```dart
      final client = GoogleOAuth2Client(
        customUriScheme: 'my.app',
        redirectUri: 'my.app:/',
      );
      final oauth2Helper = OAuth2Helper(
        client,
        grantType: OAuth2Helper.AUTHORIZATION_CODE,
        clientId:
            '<mytoken>.apps.googleusercontent.com',
        scopes: ['https://www.googleapis.com/auth/userinfo.profile'],
      );
```
2. Try to get resource
3. Complete auth flow
4. `refresh_token` is returned from Google api, and `access_token` is correctly used
5. Token expired, e.g. `tknResp.expiresIn = 0`, `tknResp.expirationDate = DateTime(2020)`
6. Try to get resource again
7. `refresh_token` is used to get new token
8. Google returns new `access_token` but without `refresh_token`
9. `refresh_token: null` is written to store
10. Token expired again
11. Try to get resource
12. Error happens because here https://github.com/teranetsrl/oauth2_client/blob/master/lib/oauth2_client.dart#L170 refreshToken is null

---

So the possible solution is to use refresh_token from previous token is there is no refresh_token in new one.

**Comment by okrad** [comment]
Thank you @iofjuupasli for the detailed ticket, now it should be solved. Can you confirm it?
