### ISSUE TITLE
Should I be able to use this with Azure AD B2C?

### ISSUE THREAD

**Issue by kentcb** [teranetsrl/oauth2_client#18]
Hi,

Thanks for this lib. It looks, in theory, like I should be able to use this with Azure. But I'm having trouble getting it to cooperate. Even though I can successfully authenticate, the redirect causes a `404` rather than the callback scheme being recognized and causing the resumption of the sign-in process.

Let me state up-front that one possible factor in this issue is that the Azure portal _requires_ a leading `https://` on any redirect URLs you enter. Therefore, I have to enter `https://myapp.azurewebsites.net/:/oauth2redirect` rather than `myapp.azurewebsites.net/:/oauth2redirect`.

The `404` looks like this:

![image](https://user-images.githubusercontent.com/1901832/83936557-155f6700-a808-11ea-94b4-f7c75a8c5069.png)

(I'm referring to the blurred component of the URIs as `myapp` throughout this issue)

I have tried all these things as values for the `android:scheme`:

* `myapp.azurewebsites.net`
* `https://myapp.azurewebsites.net`
* `https://myapp.azurewebsites.net/`

Nothing seems to pick up the redirect when using the following:

```dart
customUriScheme: 'https://myapp.azurewebsites.net/',
redirectUri: 'https://myapp.azurewebsites.net/:/oauth2redirect',
```

The same thing happens if I change the custom/redirect URIs to this (so that the `customUriScheme` _exactly_ matches what's in the manifest):

```dart
customUriScheme: 'myapp.azurewebsites.net',
redirectUri: 'https://myapp.azurewebsites.net/:/oauth2redirect',
```

Is there something I'm doing wrong here?

**Comment by kentcb** [comment]
Ooooooooooook. I think I've figured this out, but recording this in case anyone else runs into it.

So, the Azure AD has a new and "improved" experience for managing applications under AD B2C. And when I say "improved", I mean it just wasted me 4 hours of my Saturday. This is because it has nowhere to enter a callback URI for native/public authentication flows. I had to switch to the old, "legacy" experience to find the text box to enter one. Having done that, I have moved passed the above problem (I've hit another, but to do with my API's config, which I'll look at next).

Another thing that caused some confusion for me was that the README for this project includes a number of uses of `com.teranet.app:/oauth2redirect` instead of `com.teranet.app://oauth2redirect`. I think at some point I copied one of these without realizing it was missing a `/`. I assume that is unintentional?

**Comment by okrad** [comment]
Hi @kentcb, so you managed to make it work with a custom scheme? From the [Azure tutorial](https://docs.microsoft.com/en-us/azure/active-directory-b2c/signin-appauth-android?tabs=app-reg-ga#tabpanel_CeZOj-G++Q_app-reg-ga) it looks like it should work...

Thank you for reporting the typo in the README, I will fix it asap.

As for the disconnection flow, currently the library does not support OpenID Connect (I'm working on it) and consequently not even the logout flow ...

**Comment by kentcb** [comment]
@okrad Thanks for getting back to me. Yes, I did get it working once I figured out Azure's UX. I will close this issue.

As for sign out, that is a real missing piece for me, so very glad to hear it's in the works.
