### ISSUE TITLE
Docs unclear for https redirects

### ISSUE THREAD

**Issue by innocentalone** [teranetsrl/oauth2_client#19]
Sorry, but I could not find anywhere in the docs, how to handle `https` redirects.

Actually, my OAuth2 server requires the redirect URI to be an `https` one and here, the example only shows how to handle custom URI schemes. Like `myapp`, or `com.teranet.app`.

Which values should be put in `customUriScheme` and `redirectUri` for this use case??

**Comment by myasinu** [comment]
You don't have to use htttps, why don't you try  myapp://oauth2redirect .
myapp and oauth2redirect can be anything but you have to put :// in betweeen them
Make sure the first part before :// is the same as your android:scheem in your android manifest.

**Comment by RaviKavaiya** [comment]
@myasinu I understand that we should use the custom one.
But as I told before, my OAuth app doesn't allow this. 
It needs to be an HTTPS one only...

**Comment by innocentalone** [comment]
Oh, someone just deleted a post... 🤔 May be he/she is having same problem. 

@myasinu My OAuth only allows https redirects.

**Comment by okrad** [comment]
@innocentalone, normally HTTP(S) urls are handled directly by the system browser, so to be able to intercept the redirect and "bypass" the browser you must use a "custom" url scheme...

**Comment by apoleo88** [comment]
I have the same doubt, to authenticate with google I create a new Google ID and I select `Web applications`.
It then wants to know the redirect URI, but if I enter `myapp://oauth2redirect` it gives me an error and doesn't make me save it, it says the scheme needs to be http or https.

If I don't add this authorized URI the authentication returns  
`Invalid parameter value for redirect_uri: Invalid scheme`

**Comment by okrad** [comment]
Hi @apoleo88, you just need one key... 

Make sure to select "iOS" as the Application Type and to set the _Bundle ID_ field with your custom uri scheme (for example "my.test.app").

**Comment by NiyazFazlyev** [comment]
Hi @apoleo88, did you manage to solve your problem? could you share your experience?

**Comment by apoleo88** [comment]
> 
> 
> Hi @apoleo88, did you manage to solve your problem? could you share your experience?

I didn't, I created an "Android" application on google to add the URI, and it works fine on android, but I am not using anymore this library.

**Comment by innocentalone** [comment]
@apoleo88 Can you please tell me which library you are using?
