### ISSUE TITLE
Auth0

### ISSUE THREAD

**Issue by Ferdzzzzzzzz** [teranetsrl/oauth2_client#2]
Hi there, firstly: this package looks really cool, excited to try it out. Secondly: do you have Auth0 on the roadmap? Or would it be better to wait for their dedicated SDK? (they haven't announced it yet but the rumors are strong).

**Comment by okrad** [comment]
Hi @Ferdzzzzzzzz, not a big expert of Auth0, but from my understanding it relays on OAuth2 with OpenID Connect and JWT tokens, which are both on our roadmap.
I guess once they are implemented, we could then implement a dedicated client to seamlessly integrate with Auth0.

**Comment by Ferdzzzzzzzz** [comment]
@okrad I decided to play with Auth0 and oauth2_client this weekend and found it quite easy to integrate (I think implementing a dedicated client for auth0 might be redundant as each user would still have to add their Auth0 domain), just out of interest...is there a timeline for JWT and OpenID? I'm closing this ticket as I see no use for a dedicated Auth0 client 😄

**Comment by okrad** [comment]
Hi @Ferdzzzzzzzz, OpenID implementation has already been started, hope to be able to release a basic working version in the next couple weeks.
