### ISSUE TITLE
Web view opens for every call

### ISSUE THREAD

**Issue by fringefilmsoz** [teranetsrl/oauth2_client#21]
Every call I make with a get is showing the Chrome window briefly while the request is processing.

Is this normal behaviour? If a token is passed, should it still launch the Chrome window?

I'm launching my custom client with the following function:
```
OAuth2Helper doauth({String authUrl, String tokenUrl}) {
        MyOAuth2Client client = MyOAuth2Client(
        // redirectUri: 'fhir_cerner/oauth2redirect',
        // redirectUri: '',
        // redirectUri: 'http://fhircerner/oauth2redirect',
        customUriScheme: 'fhircerner',
        authUrl: authUrl,
        tokenUrl: tokenUrl);

    OAuth2Helper oauth2Helper = OAuth2Helper(client,
        grantType: OAuth2Helper.AUTHORIZATION_CODE,
        clientId: 'xxx',
        scopes: ['user/Observation.read user/MedicationHistory.read user/Patient.read', 
        '&aud=${Settings().baseUrl}'
        ]);
    return oauth2Helper;
  }
```
And making calls with:
```
      http.Response result =
          await meta.oAuth2Helper.get(url, headers: Settings().headers);
```

**Comment by okrad** [comment]
Hi @fringefilmsoz, you are absolutely right, I didn't notice it...
It's a regression that's been introduced in the last release, now it should be fixed.
Can you confirm it?

**Comment by fringefilmsoz** [comment]
It hasn't resolved my issue. 
I tried using older versions and all had the same behaviour. So, I'm at a bit of a loss.

**Comment by okrad** [comment]
Ok... Looking back at your code I suspect the problem could be in how you pass the scopes to the helper...

Can you try with:
```
    OAuth2Helper oauth2Helper = OAuth2Helper(client,
        ...
        scopes: ['user/Observation.read', 'user/MedicationHistory.read', 'user/Patient.read', 
        '&aud=${Settings().baseUrl}'
        ]);
```

Instead of:
```
    OAuth2Helper oauth2Helper = OAuth2Helper(client,
        ...
        scopes: ['user/Observation.read user/MedicationHistory.read user/Patient.read', 
        '&aud=${Settings().baseUrl}'
        ]);
```

Btw, is _&aud=${Settings().baseUrl}_ really a scope?

**Comment by fringefilmsoz** [comment]
Thanks so much for your help.

Updated as per below with the same behaviour.

It seems like a hack to use the scopes to append an additional parameter in my last scope. I wonder if that's breaking it?

Should there be an ability to pass additional parameters after scopes?

Cerner requires it to prevent man in the middle interception.

```
OAuth2Helper oauth2Helper = OAuth2Helper(client,
        grantType: OAuth2Helper.AUTHORIZATION_CODE,
        clientId: 'XXXXXXX',
        scopes: [
          'user/Observation.read',
          'user/MedicationHistory.read',
          'user/Patient.read',
          '&aud=${Settings().baseUrl}'
        ]);
```

**Comment by okrad** [comment]
Yes, the "aud" parameter doesn't have to be passed as a scope, but as a queryString param.
So, one thing we need to do is find a way to pass custom parameters to the authorization request. This shouldn't be particularly difficult and shouldn't take too long...

Anyway this won't completely solve your problem... Can you elaborate a little more on how it occours?
Did you pass through the authorization process (cerner login sceen) at all? If so, did you check if an actual access token is returned?

**Comment by fringefilmsoz** [comment]
Yes, first time I'm asked to log in. Log in is successful.
Each call using the helper then causes the webview to open and then close.
E.g. I make three successive calls for data the webview opens and then closes three times. Each time data is returned as expected.

How do I check if an access token is returned? And maybe if it's stored?
Thanks Duncan

**Comment by okrad** [comment]
I just published the new release (1.4.0) that lets you pass custom parameters both to the authorization request and to the access token request.
For example:

```dart
OAuth2Helper oauth2Helper = OAuth2Helper(client,
  grantType: OAuth2Helper.AUTHORIZATION_CODE,
  clientId: 'YOUR_CLIENT_ID',
  scopes: [
    'user/Observation.read',
    'user/MedicationHistory.read',
    'user/Patient.read',
  ],
  authCodeParams: { //Or accessTokenParams, depending on when you want your param to be sent...
    'aud': sett.Settings().baseUrl
  });
```
So, let's try a couple of things and see if we can understand what's happening...

First, you can check if a token is currently stored with:

```dart
var tknResp = oauth2Helper.getTokenFromStorage();
print(tknResp.accessToken);
print(tknResp.expirationDate);
print(tknResp.scope);
```

Then we can try to force the retrieval of a new token, skipping the helper altogether, and see what the server is returning:

```dart
var tknResp = await client.getTokenWithAuthCodeFlow(
  clientId: 'YOUR_CLIENT_ID',
  clientSecret: 'YOUR_CLIENT_SECRET',
  scopes: [
    'user/Observation.read',
    'user/MedicationHistory.read',
    'user/Patient.read',
  ],
  authCodeParams: {'aud': sett.Settings().baseUrl});

print(tknResp.httpStatusCode);
print(tknResp.error);
print(tknResp.accessToken);
print(tknResp.expirationDate);
print(tknResp.scope);
```

**Comment by fringefilmsoz** [comment]
Thank you, appreciate the very quick update.

Updated code returns the following error:
> MetaOAHelper error: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>'

```
    OAuth2Helper oauth2Helper = OAuth2Helper(client,
        grantType: OAuth2Helper.AUTHORIZATION_CODE,
        clientId: 'XXXXX',
        scopes: [
          'user/Observation.read',
          'user/MedicationHistory.read',
          'user/Patient.read',
          'user/Appointment.read',
          // '&aud=${Settings().baseUrl}'
        ],
        authCodeParams: {
          'aud': sett.Settings().baseUrl
          }
        );
```

**Comment by okrad** [comment]
Ah yes, I see... There was a minor issue in the latest updates... 

I just pushed a fix, can you try with the new version?

**Comment by fringefilmsoz** [comment]
Thanks, Can confirm v1.4.1 resolves the above error.

Following error occurs on the tknResp:

> NoSuchMethodError: The getter 'accessToken' was called on null.

**Comment by okrad** [comment]
This means no token has been memorized in the store... That's why you see the browser window opening up at every request. 
I guess the browser sends a session cookie that had been created during the last login, and so the authorization server just redirects you to the redirect_uri without asking for a new login process.

What's the output of the last snippet of code, i.e.:

```dart
var tknResp = await client.getTokenWithAuthCodeFlow(
  clientId: 'YOUR_CLIENT_ID',
  clientSecret: 'YOUR_CLIENT_SECRET',
  scopes: [
    'user/Observation.read',
    'user/MedicationHistory.read',
    'user/Patient.read',
  ],
  authCodeParams: {'aud': sett.Settings().baseUrl});

print(tknResp.httpStatusCode);
print(tknResp.error);
print(tknResp.accessToken);
print(tknResp.expirationDate);
print(tknResp.scope);
```

**Comment by fringefilmsoz** [comment]
Here's the output i receive, which appears to include a valid token. 

```
I/flutter (29456): 200
I/flutter (29456): null
I/flutter (29456): eyJraWQiOiIyMDIwLTA2LTIwVDA2OjEyOjM0LjUxMi5lYyIsInR5cCI6IkpXVCIsImFsZyI6IkVTMjU2In0.eyJzdWIiOiJwb3J0YWwiLCJ1cm46Y29tOmNlcm5lcjphdXRob3JpemF0aW9uOmNsYWltcyI6eyJ2ZXIiOiIxLjAiLCJ0bnQiOiIwYjhhMDExMS1lOGU2LTRjMjYtYTkxYy01MDY5Y2JjNmIxY2EiLCJhenMiOiJ1c2VyXC9PYnNlcnZhdGlvbi5yZWFkIHVzZXJcL1BhdGllbnQucmVhZCJ9LCJhenAiOiI3Y2I3ODI3Yy1hMDM0LTQxODAtOGMzMS0yNGM0NzMzNjAzMWUiLCJpc3MiOiJodHRwczpcL1wvYXV0aG9yaXphdGlvbi5zYW5kYm94Y2VybmVyLmNvbVwvIiwiZXhwIjoxNTkyNzM1ODAwLCJpYXQiOjE1OTI3MzUyMDAsImp0aSI6IjZiNjAwZjcxLTIyYTEtNGY1Zi05NTNkLTQ2NWRmMzliYjFlZSIsInVybjpjZXJuZXI6YXV0aG9yaXphdGlvbjpjbGFpbXM6dmVyc2lvbjoxIjp7InZlciI6IjEuMCIsInByb2ZpbGVzIjp7InNtYXJ0LXYxIjp7ImF6cyI6InVzZXJcL09ic2VydmF0aW9uLnJlYWQgdXNlclwvUGF0aWVudC5yZWFkIn19LCJjbGllbnQiOnsibmFtZSI6IkNlcm5lciBUZXN0IEFwcCIsImlkIjoiN2NiNzgyN2MtYTAzNC00MTgwLThjMzEtMjRjNDczMzYwMzFlIn0sInVzZXIiOnsicHJpbmNpcGFsIjoicG9ydGFsIiwicGVyc29uYSI6InByb3ZpZGVyIiwiaWRzcCI6IjBiOGEwMTExLWU4ZTYtNGMyNi1hOTFjLTUwNjljYmM2YjFjYSIsInNlc3Npb25JZCI6IjBmZDQyMzkwLWY0ZjMtNDU5Yy1hMWUyLTVjZmY4NzFmMTQyNyIsInByaW5
I/flutter (29456): 2020-06-21 20:36:11.045179
I/flutter (29456): [user/Observation.read, user/Patient.read]
```

**Comment by fringefilmsoz** [comment]
All is working as expected now. I think i had an issue with an incorrect scope.
Thanks for your help.

**Comment by fringefilmsoz** [comment]
All working

**Comment by okrad** [comment]
Hi @fringefilmsoz, I'm glad you solved your issue.

It looks like you were requesting 3 scopes but the server granted only 2 of them...
Since tokens gets stored using the granted scopes as the key, every time you were performing a request the library couldn't find a  token in the storage for the 3 scopes, so it was trying to fetch a new token.

**Comment by fringefilmsoz** [comment]
Thanks so much again.
