### ISSUE TITLE
HTTP Error 500.35-ANCM

### ISSUE THREAD

**Issue by jainilparikh** [teranetsrl/oauth2_client#23]
Hi ,
So I am using your plugin for a flutter application.
This is my version   oauth2_client: ^1.2.2

I call my API's by building a custom oauth2Class similar to this code here:
`
class MyOAuth2Client extends OAuth2Client {
  MyOAuth2Client({@required String redirectUri, @required String customUriScheme}): super(
    authorizeUrl: 'https://...', //Your service's authorization url
    tokenUrl: 'https://...', //Your service access token url
    redirectUri: redirectUri,
    customUriScheme: customUriScheme
  );
}
`
But the apis function properly for sometime but later give an error: HTTP Error 500.35 ANCM Multiple In process Applications in same process. Till where I understand this could be  a server side error.

But my API's and server side codes are correct. Is there anything in the oauth2_client that can cause this? something related to refreshing the tokens? 

This API problem get fixed on uninstalling the app and reinstalling it. I highly doubt it can be a server side error .

Could you please tell me any potential causes/bugs that I might have to consider while working with oauth2_client ?

**Comment by okrad** [comment]
Hi @jainilparikh, I can't think of anything that could cause such an issue. 
As you said, it seems a server side error... I suppose you already searched the internet for a potential solution... Anyway, if it can be of any help I [found this](https://stackoverflow.com/questions/58246822/http-error-500-35-ancm-multiple-in-process-applications-in-same-process-asp-ne).

Another thing you could try is updating to the latest version (1.4.1 atm) of the library...

**Comment by jainilparikh** [comment]
thanks @okrad for clearing my doubt regarding the usage of the plugin . I assume its a server side error itself.
