### ISSUE TITLE
iOS App crashes

### ISSUE THREAD

**Issue by phamotcreations** [teranetsrl/oauth2_client#3]
Hi,
I am using AUTHORIZATION_CODE grantType and just started using this library. My iOS app crashes when I call helper.get(). 
I am using v1.1.2

**Comment by okrad** [comment]
Hi @phamotcreations, can you try updating your ios/Podfile, and set the property:

```
platform :ios, '11.0'
```

**Comment by okrad** [comment]
Hi @phamotcreations, did you manage to make it work? Can I close the issue?

**Comment by jimad7** [comment]
The iOS App crashes on this row (for me) 

final result = await FlutterWebAuth.authenticate(
        url: authorizeUrl, callbackUrlScheme: customUriScheme);

Everything else works and no errors on android.

**Comment by jimad7** [comment]
Hi again, sorry for hijacking this issue, but i found the error that caused the crash on ios in my app. I accidentally added a blank space in the scope parameters for openid: ['openid ', 'profile']. That extra space character crashed the app. Sorry!

**Comment by okrad** [comment]
Hi @jimad7, thank you for letting me know. I just published a fix that trims the scopes parameter.

**Comment by prooshani** [comment]
> Hi @phamotcreations, can you try updating your ios/Podfile, and set the property:
> 
> ```
> platform :ios, '11.0'
> ```

Hi, 
I am using this library and on android side everything works fine (OpenID)
But in iOS part this specific part of code is not working like android one and it requests for credentials everytime the user wants to enter:

OAuth2_client.dart -> 

```
    // Present the dialog to the user
    final result = await webAuthClient.authenticate(
        url: authorizeUrl, callbackUrlScheme: customUriScheme, redirectUrl: redirectUri, opts: webAuthOpts);
```

I tried to set platform in ios/podfile to 11.0 but at the moment minimum ios platform version is 12.0
