### ISSUE TITLE
AAD authentication returns integer values in quotes - these could be handled better

### ISSUE THREAD

**Issue by gocarnetdev** [teranetsrl/oauth2_client#31]
I get string/int type conversion exceptions in access_token_response.dart starting at line 39 because the map contains "expires_in"->"3599" in quotes, same for ext_expires_in, expires_on, and not_before.  This comes from using https://login.microsoftonline.com/ as the authorize URL.

**Comment by okrad** [comment]
Hi @gocarnetdev, you are right, we should cast the "expires_in" value to an int... 
As for the other parameters ("ext_expires_in", "expires_on", "not_before"), these are not standard and are not considered at all...

**Comment by okrad** [comment]
Hi @gocarnetdev, can I consider the issue closed?
