### ISSUE TITLE
is there an example of this working with AAD

### ISSUE THREAD

**Issue by ivanlamont** [teranetsrl/oauth2_client#34]
I can get Azure Active Directory to accept my request and send me a token, but it always responds with the default audience, the Graph API (aud: 00000002-0000-0000-c000-000000000000).  I am unable to get it to give me a token for other resources, APIs I expose on other apps.  Is this currently possible?  If so, any chance of an example?

Thanks

Ivan

**Comment by okrad** [comment]
Hi @ivanlamont , 
sorry I'm not an expert at all on AAD...
I don't think I fully understand your problem, but if you need to authorize access to more resources you can pass all of the required scopes to the client (or the helper) as a List.

I took a look to the AAD documentation, it seems the authorization and token urls need to include a "tenant", that from what I understand is a sort of "directory"... Given this, I would probably define an AAD client like this:

```dart
import 'package:meta/meta.dart';
import 'package:oauth2_client/oauth2_client.dart';

class AADOAuth2Client extends OAuth2Client {
  AADOAuth2Client(
      {@required String redirectUri,
      @required String customUriScheme,
      String tenant = 'common'})
      : super(
            authorizeUrl: 'https://login.microsoftonline.com/' +
                tenant +
                '/oauth2/v2.0/authorize',
            tokenUrl: 'https://login.microsoftonline.com/' +
                tenant +
                '/oauth2/v2.0/token',
            redirectUri: redirectUri,
            customUriScheme: customUriScheme) {
  }
}
```

And then I would use it as:

```dart
var client = AADOAuth2Client(
  redirectUri: 'mytestapp://oauth2redirect', customUriScheme: 'mytestapp', tenant: 'mytenant');
var hlp = OAuth2Helper(client,
  clientId: clientId, clientSecret: clientSecret, scopes: ['scope1', 'scope2']);

var tokenResp = await hlp.getToken();
```

But again, not an AAD expert...

**Comment by ivanlamont** [comment]
Success!  I did get it to return access to the required audience, with some minor modifications to your suggestion.  I should have mentioned - I am using the client credentials flow.  So, the redirect and customUriSchemes are not needed, indeed they need to be blank.  And we need to force the Client Credentials grant type.  Here's my final code:

`
  Future<void> requestToken() async {

    var client = AADOAuth2Client(
        tenant: _myTenantId);
    var hlp = OAuth2Helper(client,
        clientId: _myClientId, clientSecret: _myClientSecret, grantType: OAuth2Helper.CLIENT_CREDENTIALS, scopes: [_resourceRootUri + '/.default']);

    await hlp.getToken().then(checkResponse);
  }

}

class AADOAuth2Client extends OAuth2Client {
  static final String _myAuthority = "https://login.microsoftonline.com/";

  AADOAuth2Client(
      {@required String tenant})
      : super(
        authorizeUrl: _myAuthority + tenant + '/oauth2/v2.0/authorize',
        tokenUrl: _myAuthority + tenant + '/oauth2/v2.0/token',
        redirectUri: "",
        customUriScheme: "") {
  }

`
