### ISSUE TITLE
Add a flag to disable PKCE when using OAuth2Helper

### ISSUE THREAD

**Issue by pposca** [teranetsrl/oauth2_client#35]
I am consuming an API that does not support PKCE and returns a 400 status code when trying to get the token using OAuth2Helper.

I see there is a param called enablePKCE to use when calling directly OAuth2Client.getTokenWithAuthCodeFlow, but I cannot find any way to disable PKCE when using OAuth2Helper.

Am I missing anything?

**Comment by okrad** [comment]
Hi @pposca, I just released a new version...
Now you can disable PKCE by passing `enablePKCE: false` to the helper constructor. Can you try it out?

**Comment by pposca** [comment]
Thanks, @okrad. It works perfectly.
