### ISSUE TITLE
Optional state parameter

### ISSUE THREAD

**Issue by SnailVanquisher** [teranetsrl/oauth2_client#38]
I understand that the state parameter is recommended and is good for security, but I have come across certain APIs that don't expect the state parameter, so they don't return it on the redirect, causing the auth flow to break. Would you be open to having it be optional, similar to enablePKCE? I'd be happy to make the changes and open a pull request, as I'm already using a local modified copy with these changes.

**Comment by okrad** [comment]
Hi @SnailVanquisher, I guess it would indeed be useful in some occasions, I'd gladly merge your PR! 

The parameter should be available both in the OAuth2Client and in the OAuth2Helper class, just as the enablePKCE param.

Thank you!
