### ISSUE TITLE
Does not redirect

### ISSUE THREAD

**Issue by casetofon** [teranetsrl/oauth2_client#39]
Using the code provided in the example with the Google App, it does open the browser and exchange the code, but instead of returning to the app once the permission is provided, it just shows the token in the browser and asks that you copy/paste it back into your app. 
[screenshot](https://i.ibb.co/MRsW6Nc/backto.jpg)

**Comment by okrad** [comment]
Hi @casetofon, what redirect uri did you specify in the application registration form? You should use a custom uri with a scheme that's *not* http(s), for example my.test.app://oauth2redirect.

**Comment by okrad** [comment]
If you really want/need to use an https redirect uri, I just updated the README to explain how to do it (by means of Android App Links).

**Comment by casetofon** [comment]
Thanks okrad, I figured it out: the issue was a missing / (slash) on the string value of the redirect uri.
