### ISSUE TITLE
Token not getting stored

### ISSUE THREAD

**Issue by ujnamss** [teranetsrl/oauth2_client#44]
Hi @okrad,

Thanks for the wonderful library. It has significantly simplified my implementation of Microsoft authentication integration.

I have a similar problem to the one mentioned at https://github.com/teranetsrl/oauth2_client/issues/27.

`    this._oauth2Client = OAuth2Client(
        authorizeUrl:
            "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        redirectUri: "msauth.me.test.appv1://auth",
        customUriScheme: "msauth.me.test.appv1");
    this._oauth2Helper = OAuth2Helper(
      this._oauth2Client,
      grantType: OAuth2Helper.AUTHORIZATION_CODE,
      clientId: '<client id>',
      scopes: [
        'https://graph.microsoft.com/Calendars.Read',
        'https://graph.microsoft.com/Calendars.Read.Shared',
        'https://graph.microsoft.com/email',
        'https://graph.microsoft.com/Mail.ReadBasic',
        'https://graph.microsoft.com/profile',
        'https://graph.microsoft.com/User.Read'
      ],
    );`

Every time i invoke a "helper.get", it redirects to oauth popup asking to "sign in" again.
`    http.Response resp =
        await this._oauth2Helper.get("https://graph.microsoft.com/v1.0/me");
    Map<String, dynamic> user = convert.jsonDecode(resp.body);
    print(user);`

I tried debugging by invoking "getToken" even that triggers an oauth popup - which leads me to believe that it is a token not being stored problem.

Looking forward for any suggestions to solve it on my end

Thanks
Manju

**Comment by ujnamss** [comment]
I tried using setAuthorizationParams as well:
`    this._oauth2Helper = OAuth2Helper(this._oauth2Client);
    this._oauth2Helper.setAuthorizationParams(
      grantType: OAuth2Helper.AUTHORIZATION_CODE,
      clientId: '<client_id>',
      scopes: [
        'https://graph.microsoft.com/Calendars.Read',
        'https://graph.microsoft.com/Calendars.Read.Shared',
        'https://graph.microsoft.com/email',
        'https://graph.microsoft.com/Mail.ReadBasic',
        'https://graph.microsoft.com/profile',
        'https://graph.microsoft.com/User.Read'
      ],
    );`

No luck.

I am testing this on an ios Emulator (if that helps)

**Comment by ujnamss** [comment]
Tried with both:`oauth2_client: ^1.5.1` and `oauth2_client: ^1.5.0` - no luck

**Comment by okrad** [comment]
Hi @ujnamss, this can happen when you request some scopes but then the server returns an authorization only for a subset of them, for example if one of more scopes are incorrect or misspelled....

What's the output of the following code?

```dart
this._oauth2Client = OAuth2Client( 
  authorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize", 
  tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token", 
  redirectUri: "msauth.me.test.appv1://auth", 
  customUriScheme: "msauth.me.test.appv1"); 

var tknResp = await client.getTokenWithAuthCodeFlow(
  clientId: 'YOUR_CLIENT_ID',
  scopes: [
  'https://graph.microsoft.com/Calendars.Read', 
  'https://graph.microsoft.com/Calendars.Read.Shared', 
  'https://graph.microsoft.com/email', 
  'https://graph.microsoft.com/Mail.ReadBasic', 
  'https://graph.microsoft.com/profile', 
  'https://graph.microsoft.com/User.Read' 
  ]);

print(tknResp.httpStatusCode);
print(tknResp.error);
print(tknResp.expirationDate);
print(tknResp.scope);
```

**Comment by ujnamss** [comment]
hi @okrad,

Thanks for the note. I ran the sample and seems like everything is good.
`
flutter: 200
flutter: null
flutter: 2020-10-04 11:49:58.047702
flutter: [email, profile, openid, https://graph.microsoft.com/Calendars.Read, https://graph.microsoft.com/Calendars.Read.Shared, https://graph.microsoft.com/Mail.ReadBasic, https://graph.microsoft.com/User.Read]
`

**Comment by okrad** [comment]
Ok, so the server, for whatever reason, is returning different scopes than you requested...

Can you try using those scopes in your request?

```dart
this._oauth2Client = OAuth2Client( authorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize", 
  tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token", 
  redirectUri: "msauth.me.test.appv1://auth", 
  customUriScheme: "msauth.me.test.appv1"); 

this._oauth2Helper = OAuth2Helper( this._oauth2Client, 
  grantType: OAuth2Helper.AUTHORIZATION_CODE, 
  clientId: '<client id>', 
  scopes: [ 
    'email', 
    'profile', 
    'openid', 
    'https://graph.microsoft.com/Calendars.Read', 
    'https://graph.microsoft.com/Calendars.Read.Shared', 
    'https://graph.microsoft.com/Mail.ReadBasic', 
    'https://graph.microsoft.com/User.Read'
  ]);
```

**Comment by ujnamss** [comment]
oh! sure. I have actually resorted to not using the auth2 helper. I wrote a small piece of code to refreshToken etc myself using the client alone.

I will give this a try in a bit. Hope that is ok.

**Comment by ujnamss** [comment]
hi @okrad - scope names were the issue indeed. After changing the scopes, the issue is resolved.
