### ISSUE TITLE
tokenType is null and token is not saved to storage

### ISSUE THREAD

**Issue by TonySpegel** [teranetsrl/oauth2_client#46]
Hi there,

great library! I'm running into a few issues while using it to communicate with Slack's API.
While working with the helper class I've noticed that the tokenType is not set to bearer and instead is set to `null`.

Steps which might be useful to reproduce:

1. Own a Slack workspace
2. Create your own Slack app
3. Set its scope to users.profile:write
4. Add a redirect URL and configure it according to your OS in the corresponding file

I'm using it like this:
```Dart
class TelestoOAuth2Client extends OAuth2Client {
  TelestoOAuth2Client(
      {@required String redirectUri, @required String customUriScheme})
      : super(
          authorizeUrl: 'https://slack.com/oauth/authorize',
          tokenUrl: 'https://slack.com/api/oauth.access',
          customUriScheme: 'slack.status.app',
          redirectUri: 'slack.status.app://oauth2redirect',
        );
}

OAuth2Client telestoClient = TelestoOAuth2Client(
    customUriScheme: 'slack.status.app',
    redirectUri: 'slack.status.app://oauth2redirect');

OAuth2Helper oauth2Helper = OAuth2Helper(telestoClient,
    grantType: OAuth2Helper.AUTHORIZATION_CODE,
    clientId: 'secret',
    clientSecret: 'secret',
    scopes: ['users.profile:write']); 
```
The method itself:
```Dart
Future<http.Response> setSlackStatus(String statusText, String statusEmoji,
    // AccessTokenResponse token,
    {int statusExpiration = 0}) async {
  // var tokenString = token.accessToken;

  final res = await oauth2Helper.post(
      Uri.encodeFull('https://slack.com/api/users.profile.set'),
      headers: {
        'Content-Type': 'application/json; charset=UTF-8',
        // 'Authorization': 'Bearer $tokenString',
      },
      body: jsonEncode({
        'profile': {
          'status_text': statusText,
          'status_emoji': ':$statusEmoji:',
          'status_expiration': statusExpiration,
        }
      }));

  print(res.statusCode);

  return res;
}
```
As you can see I've commented out some lines, with these lines it's working fine but that's the task of the helper class to manage the token.

When calling the method like this:
```Dart
main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // AccessTokenResponse token = await oauth2Helper.fetchToken();
  // http.Response res = await setSlackStatus('WE', 'cat', token);

  http.Response res = await setSlackStatus('WE', 'cat');

  print(res.body);
  print(res.headers);
  print(res.statusCode);

  print('======');

  http.Response res2 = await setSlackStatus('WE', 'dog');
  print(res2.body);
  print(res2.headers);
  print(res2.statusCode);
}
```
I will get asked twice to accept the API request. Also when I manipulate oauth2_helper.dart to set `tknResp.tokenType` to `bearer` at least the request itself works. Is there a way to have a option which sets the token to be a bearer type?

Also do you have any ideas why it doesn't store the token in the storage?

**Comment by okrad** [comment]
Hi @TonySpegel, I suspect the issue is related to the token not getting stored, and this usually means that the scopes are not correct or somehow different from the ones granted on the server.

Can you take a look at the (just added) [FAQ](https://github.com/teranetsrl/oauth2_client#faq) section of the README and try out the suggested approach?

**Comment by TonySpegel** [comment]
@okrad Thanks for your help. Okay I did miss a scope (`identify`) and adding that seemed to work, I was able to make two requestions without Slack asking me twice for my authentication. But I think this was just working because I've set`tknResp.tokenType` to `bearer` by myself in  `oauth2_helper.dart` and Flutter didn't got the change after I changed it back. Okay so my code pretty much stays the same but I've added another scope. 
Debugging `oauth2_helper.dart` at line 91 tells me that the property `tokenType` in `tknResp` is `null`. 

Assuming that the scope was the issue, my code is correct?

**Comment by okrad** [comment]
Not sure I understand... Aren't you able to make any request at all or is it still asking you for authorization at every request?

Moreover, the Bearer token type in the helper should [already be set](https://github.com/teranetsrl/oauth2_client/blob/bf8e68678b1e0ce58c6b34e22c438f25754b12a8/lib/oauth2_helper.dart#L202)...

**Comment by TonySpegel** [comment]
Running my code as it is `tknResp.tokenType` is null and the whole request therefore fails
![image](https://user-images.githubusercontent.com/1145514/95716987-8f977080-0c6c-11eb-979c-d47be438a704.png)
That's the error log for that:
```
E/flutter ( 4661): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'toLowerCase' was called on null.
E/flutter ( 4661): Receiver: null
E/flutter ( 4661): Tried calling: toLowerCase()
E/flutter ( 4661): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5))
E/flutter ( 4661): #1      AccessTokenResponse.isBearer 
package:oauth2_client/access_token_response.dart:143
E/flutter ( 4661): #2      OAuth2Helper.getToken 
package:oauth2_client/oauth2_helper.dart:91
E/flutter ( 4661): <asynchronous suspension>
E/flutter ( 4661): #3      OAuth2Helper.post 
package:oauth2_client/oauth2_helper.dart:199
E/flutter ( 4661): #4      setSlackStatus 
package:flutterSlackStatus/main.dart:36
E/flutter ( 4661): #5      main 
package:flutterSlackStatus/main.dart:71
```

When setting this myself (in oauth2_helper.dart) it just works, so like this:
`tknResp.tokenType = 'Bearer';`

I'm out of ideas, I think there isn't much for me to do about it.

**Comment by okrad** [comment]
Hey @TonySpegel, I think I got it...
It seems that the access token response returned by the Slack authorization server doesn't contain the "token_type" parameter, that is mandatory by the OAuth2 specs. 

To overcome these situations, I added a fallback check that sets the token_type to "Bearer" if it is not set.

Can you try it out and see if it works?

**Comment by TonySpegel** [comment]
Is that already included in the latest version? I've upgraded to 1.6.0.
The bearer token seems to be fixed but it still for my permission for every request I make.
```Dart
await setSlackStatus('Library', 'cat');
// -> Slack asks for my permssion 
await setSlackStatus('Living room', 'cat2');
// -> Slack asks for my permssion 
```

**Comment by okrad** [comment]
Seems strange... In my tests the helper uses the same token without forcing me to authenticate with Slack twice.

Are you still passing on both the scopes (```identify``` and ```users.profile:write```)?

**Comment by TonySpegel** [comment]
I do. That's the complete code:
```Dart
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:oauth2_client/oauth2_client.dart';
import 'package:meta/meta.dart';
import 'package:oauth2_client/oauth2_helper.dart';
import 'package:http/http.dart' as http;

class TelestoOAuth2Client extends OAuth2Client {
  TelestoOAuth2Client(
      {@required String redirectUri, @required String customUriScheme})
      : super(
          authorizeUrl: 'https://slack.com/oauth/authorize',
          tokenUrl: 'https://slack.com/api/oauth.access',
          customUriScheme: 'slack.status.app',
          redirectUri: 'slack.status.app://oauth2redirect',
        );
}

OAuth2Client telestoClient = TelestoOAuth2Client(
    customUriScheme: 'slack.status.app',
    redirectUri: 'slack.status.app://oauth2redirect');

OAuth2Helper oauth2Helper = OAuth2Helper(telestoClient,
    grantType: OAuth2Helper.AUTHORIZATION_CODE,
    clientId: 'secret',
    clientSecret: 'secret',
    scopes: ['identify', 'users.profile:write']);

Future<http.Response> setSlackStatus(String statusText, String statusEmoji,
    // AccessTokenResponse token,
    {int statusExpiration = 0}) async {
  // var tokenString = token.accessToken;

  final res = await oauth2Helper.post(
      Uri.encodeFull('https://slack.com/api/users.profile.set'),
      headers: {
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode({
        'profile': {
          'status_text': statusText,
          'status_emoji': ':$statusEmoji:',
          'status_expiration': statusExpiration,
        }
      }));

  return res;
}

main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await setSlackStatus('Library', 'cat');
  // -> Slack asks for my permssion
  await setSlackStatus('Living room', 'cat2');
  // -> Slack asks for my permssion
}
```

This is the behaviour in a virtual device and on my physical Pixel 3, I can't test

**Comment by okrad** [comment]
I tried your code, only the first request is asking for permission...

What happens if you run it on a newly created virtual device?

**Comment by TonySpegel** [comment]
I've deleted all of my virtual devices and created a new one and also recorded the process (resolution isn't that good but it's visible what happens. the loop begins/ends when it switches back to the tab next to the AVD)
![recordedVideoScaled](https://user-images.githubusercontent.com/1145514/96228974-9a1c7780-0f96-11eb-9067-368aa4fe306b.gif)

**Comment by TonySpegel** [comment]
I've deleted all of my virtual devices and created a new one and also recorded the process (resolution isn't that good but it's visible what happens. the loop begins/ends when it switches back to the tab next to the AVD)
![recordedVideoScaled](https://user-images.githubusercontent.com/1145514/96228974-9a1c7780-0f96-11eb-9067-368aa4fe306b.gif)

**Comment by okrad** [comment]
What gets printed if you run this code after the first call to setSlackStatus:
```dart
var tkn = oauth2Helper.getToken();

print(tkn.accessToken);
print(tkn.expiresIn);
print(tkn.scope);
```

**Comment by TonySpegel** [comment]
```Bash
I/flutter ( 2891): xoxp-secret
I/flutter ( 2891): null
I/flutter ( 2891): [identify, users.profile:write, identity.basic, identity.email, identity.team]
```
These scopes are new, aren't they? I think it's working now.. I'll test it a few times and report back if it does.

**Comment by TonySpegel** [comment]
Okay there seems to be one last issue. I think the first run of the app needs to ask for only two scopes:
```
'identify',
'users.profile:write',
```
These are the scopes we identified first. After your last comment, I've figured out that it needs some more scopes.
Which are these:
```
'identify',
'users.profile:write',
'identity.basic',
'identity.email',
'identity.team'
```
When I don't add these, I've have to grant the rights for every request again. But when I add all of these scopes in the first run I'll get this error:
![image](https://user-images.githubusercontent.com/1145514/96521354-616bef00-1271-11eb-8ea0-0a643d499190.png)
Which roughly translates to: `App couldn't be installed. You can't ask for identify type of scopes and other types at the same time`

Any ideas how you would solve this? It seems like a different number of scopes is needed for different requests but I've no idea how I'd do this with your library.

**Comment by okrad** [comment]
Ok, this starts to make sense...

When you make a call through the helper, the first thing it does is to check if a valid token already exists in the storage for the service you are connecting to. If such a token is found, the second thing it does is to compare the scopes you are requesting with those that the token was granted for. If the scopes match, the stored token gets reused, otherwise a new authorization flow is started.
I don't know why (since when I tested your code I got the exact same scopes I requested back from the server) in your case the server responds with more scopes than the ones you asked for... 

What I'm thinking about is to slightly change the scopes verification routine, so that if it finds out that the scopes that are being requested are a subset of those related to the stored token, the token is considered valid.

What do you think?

**Comment by TonySpegel** [comment]
Sounds like a viable solution. It's pretty weird that it needs different scopes for the both of us. Another thing I've figured out is that the order of scopes has to be in the same order as the server telss you - do you think it would makes sense to order them by name to compare them this way? So that 
```
'identify',
'identity.basic',
'identity.email',
'identity.team'
'users.profile:write',
```
would be a valid set of scopes?
Thanks for your work I really appreciate it =)

**Comment by okrad** [comment]
Hi, can you try out the new version? As for the scopes order, it doesn't matter since the subset verification is made using set intersection that doesn't depend on the order of the elements...

**Comment by TonySpegel** [comment]
I don't have any issues anymore :). I'm already using it and it works fine so far.
Very well done

**Comment by okrad** [comment]
Fine, thank you!
