### ISSUE TITLE
Android is returning a token even when tokenStorage is not being used

### ISSUE THREAD

**Issue by SogoGolf** [teranetsrl/oauth2_client#48]
on iOS there is no issue. However on Android - after I authenticate successfully via the web popup -> the next time I restart the app and call:

```var oauth2Helper = OAuth2Helper(client, grantType: 4)```

the OAuth2Helper returns the token used in that first call above and refuses to display the web popup (via ```FlutterWebAuth```). This should NOT be happening as I understand it. Rather it should only do so when the ```tokenStorage``` property has been set. Correct ?

**Comment by okrad** [comment]
Hi @SogoGolf, how do you avoid using the tokenStorage? The OAuth2Helper job is exactly to try to reuse previously obtained tokens without activating the authorization flow, so the behaviour you are reporting seems just as expected... If no tokenStorage is passed, a default one is instantiated and used by the helper class itself.

Another thing I don't understand is the value you are using for the `grantType` parameter: the only aknowledged values are the ones defined by the 3 constants `AUTHORIZATION_CODE` (1), `CLIENT_CREDENTIALS` (2), `IMPLICIT_GRANT` (3).

**Comment by SogoGolf** [comment]
hi @okrad , very sorry for the late reply. Yes you are 100% correct - it turns out the API we we're trying to make use of did not conform to the OAuth 'standard'. Anyway since then they redid their API and now all is good.
