### ISSUE TITLE
 Endpoint with null scope in response can produce NPE

### ISSUE THREAD

**Issue by eggman87** [teranetsrl/oauth2_client#55]
This is probably just an implementation issue with the endpoint I am using (imgur.com). This oauth endpoint does not use scopes so I do not provide any scopes on my request. The token response has null in the response map returned for scopes though. This causes a NPE in the response handling code as it calls `isEmpty` on the `scope` value. 

Should be an easy fix. Will throw up a PR. 

<img width="695" alt="Screen Shot 2021-01-17 at 11 19 45 AM" src="https://user-images.githubusercontent.com/2635532/104850884-513ace80-58b7-11eb-928f-30ec06cfa662.png">

![image](https://user-images.githubusercontent.com/2635532/104850842-1173e700-58b7-11eb-830c-d6ce1cb38dfb.png)

**Comment by eggman87** [comment]
Also curious if there is any way to read the extra data in the response such as `account_id` or `account_username`?

**Comment by okrad** [comment]
Hi @eggman87, sorry for the delay... Does upgrading to the latest (null safe) version solve your problem?
As for the extra data in the response, I'm actually working on a refactorization that will allow reading non standard/custom fields.

**Comment by eggman87** [comment]
@okrad no worries. The project I was working on was a solo project so I just used a modified version of your lib (with the fix, and it worked fine), but will give the latest version a try next time I open the project (I assume it will work). 

Cool to hear about being able to access extra data, will be useful. Thanks.

**Comment by okrad** [comment]
Hi @eggman87, with the new release (2.1.0) you should be able to access custom response fields by using the ```getRespField``` method.

For example:

```dart
...
var cstFieldVal = tknResp.getRespField('my_custom_field'):
```

Hope it help!
