### ISSUE TITLE
Not able to get refresh_token - Custom aad client

### ISSUE THREAD

**Issue by Kilio22** [teranetsrl/oauth2_client#57]
Hi!

So as the title of this issue says: when I'm authenticating with the following aad custom client:
```flutter
class AzureOAuth2Client extends OAuth2Client {
  AzureOAuth2Client({@required String redirectUri, @required customUriScheme})
      : super(
            authorizeUrl: 'https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/authorize',
            tokenUrl: 'https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/token',
            redirectUri: redirectUri,
            customUriScheme: customUriScheme);
}
```
the authentication process is working, I'm getting an access_token as expected, but not any refresh_token.
Here is my sign in method:
```
signInWithMicrosoft() async {
    try {
      OAuth2Client azureClient = AzureOAuth2Client(redirectUri: 'area.app://auth', customUriScheme: 'area.app');
      OAuth2Helper oauth2Helper = OAuth2Helper(azureClient, grantType: OAuth2Helper.AUTHORIZATION_CODE, clientId: APP_ID, scopes: [
        'https://graph.microsoft.com/openid',
        'https://graph.microsoft.com/profile',
        'https://graph.microsoft.com/offline_access'
      ]);
      AccessTokenResponse accessTokenResponse = await oauth2Helper.getToken();
      log(accessTokenResponse.accessToken);
      log(accessTokenResponse.refreshToken);
    } catch (e) {
      log(e.toString());
      this.showToast("Something went wrong.");
    }
  }
```

Am i doing something wrong?

**Comment by okrad** [comment]
Hi @Kilio22, I'm sorry I never used aad. 

From the docs I see that to obtain a refresh token you need to use the "offline_access" scope, just like you are in fact doing, but it seems to me that it should be used "as is", without adding the "https://graph..." prefix. 
See for example: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-id-token-as-well-hybrid-flow

Hope it helps!

**Comment by Kilio22** [comment]
Hi!

I'm going to close this since I've found another way to handle the login process.

Thanks anyway!
