### ISSUE TITLE
OAuth2Helper does not provide PUT and PATCH requests

### ISSUE THREAD

**Issue by DeD1rk** [teranetsrl/oauth2_client#58]
## Issue

Currently, the OAuth helper does not provide PUT and PATCH requests. I think it would be nice to add support for those (and possibly also for OPTIONS, HEAD and TRACE). 

## Solution

This would be a very simple non-breaking change, as the post() method could basically be copied for PUT and PATCH. I currently extend the helper by only adding put() and patch() that are basically identical to post(), but I think it would be better to include those in the OAuth2Helper.

Any thoughts or am I overlooking a reason not to add this? Otherwise I'll make a PR soon.

**Comment by okrad** [comment]
Hi @DeD1rk, I just added the PUT, PATCH and HEAD methods to the helper class (and refactored it a bit...).
Can you check it out?

Thank you

**Comment by DeD1rk** [comment]
Hey @okrad, that looks perfect! Also nicely refactored. Thank you!
