### ISSUE TITLE
Never return from browser

### ISSUE THREAD

**Issue by pepe19000** [teranetsrl/oauth2_client#62]
I have built a simple Flutter application with a login screen what contains a "Sign in with Google" button.

This button call your sample code:

```
GoogleOAuth2Client client = GoogleOAuth2Client(
                                    customUriScheme: "http",
                                    redirectUri: "http://localhost");

 OAuth2Helper oauth2Helper = OAuth2Helper(client,
                                    grantType: OAuth2Helper.AUTHORIZATION_CODE,
                                    clientId:
                                        '{client_id}',
                                    scopes: [
                                      'https://www.googleapis.com/auth/drive.readonly'
                                    ]);

                                var resp = await oauth2Helper.get(
                                    'https://www.googleapis.com/drive/v3/files');
```

                               

And add intent-filter next to an exist <activity> tag in the 'main/Androidmanifest.xml'

```
<activity android:name="com.linusu.flutter_web_auth.CallbackActivity" >
          <intent-filter android:label="flutter_web_auth">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="http" android:host="localhost"/>
          </intent-filter>
        </activity> 
```

I tried without android:host or with my.test.app on the scheme, but it seems like my app not see my intent-filter...
When I used your sample (with my.test.app) i always get "custom scheme cannot have authority" error in the google.
So i can only using localhost for success login, but google always redirect to my "localhost" and response never come back to my app.

(the redirectUri is not exist. Just a fake address what google api can accept, so when redirect i get a "site can't be reached" error)

In Google Api Console i created an Android Credential, so i don't have secret key only a client_id.

Can you describe this package's operation?

Name of scheme on the intent-filter's data tag is a fake name? Or an exist server somewhere? 
RedirectUri is a fake site and intent handle it??

In my opinion the operation this:
Click on "Sign in with Google" button in the Android app
Browser open
Login with google account
Google redirect
Andoid app see the intent and close browser
Android app get response.

Thank you

**Comment by pepe19000** [comment]
I found the solution. I opened an issue on stackoverflow, so my answer is in it:
https://stackoverflow.com/questions/66495465/flutter-android-intent-filter-with-google-oauth/66516545#66516545

**Comment by pavan-kalyan** [comment]
Thanks @pepe19000, this helped me out.
I could not figure out why using a custom scheme with google OAuth is so ridiculously difficult on android but using the client id is an acceptable solution for now. Even konrad's oauth2_test_client repo wasn't working (but non google oauth was working fine with custom scheme).

**Comment by pepe19000** [comment]
> Thanks @pepe19000, this helped me out.
> I could not figure out why using a custom scheme with google OAuth is so ridiculously difficult on android but using the client id is an acceptable solution for now. Even konrad's oauth2_test_client repo wasn't working (but non google oauth was working fine with custom scheme).

I didn't try another non google oauth. In that case is a fake custom scheme enough?
Google always said that for fake custom scheme: "redirect uri mismatch"....

**Comment by brotkrume** [comment]
Hi, I create an account here on github, only to say: Thank you so much 😀 You helped me so much 👏

**Comment by pepe19000** [comment]
> Hi, I create an account here on github, only to say: Thank you so much 😀 You helped me so much 👏

:)
