### ISSUE TITLE
Allow custom clients to override certain aspects of response parsing to handle non-standard oauth implementations.

### ISSUE THREAD

**Issue by jun-exposure** [teranetsrl/oauth2_client#70]
I have created a PR #69 to address this.

Some oauth servers do not fully implement the standard, or have additional requirements. Refactored AccessTokenResponse, OAuth2Client, and TokenStorage to allow subclass to implement those custom behaviors. In particular, these are the "non-standard" implementations:

Requires scopes to be a comma separated string, rather than a list of strings
Additional information in access token response, such as userid
HTTP response status code included in the body, while the response status code is set to 200 even with error
Response has an extra 'body' element, which contains the actual content that should be in the top level response.body
These are all idiosyncrasies from Withings oauth implementation. Primarily, a subclass of AccessTokenResponse is required to parse these implementation details. The changes in this PR refactors some of detailed parsing, etc code into their own methods so that subclasses can overwrite the standard based parsing implemented by the base classes in oauth2_client.

**Comment by okrad** [comment]
HI @jun-exposure, I just published a new release (2.1.0) that should address your needs. 

In brief:
* to use another scope separator, you can pass the client constructor a new parameter: ```scopeSeparator: ','```
* to access custom/non standard fields in the token response, you can use the ```OAuth2Response.getRespField()``` method
* you can override the ```OAuth2Client.http2TokenResponse``` method to parse the "body" element

For example:
```dart
class WithingsOAuthClient extends OAuth2Client {
  static final String withingsAuthorizeUrl = 'https://account.withings.com/oauth2_user/authorize2';
  static final String withingsTokenUrl = 'https://wbsapi.withings.net/v2/oauth2';

  WithingsOAuthClient({required String redirectUri, required String withingsUriScheme}): super(
    authorizeUrl: withingsAuthorizeUrl,
    tokenUrl: withingsTokenUrl,
    redirectUri: redirectUri,
    customUriScheme: withingsUriScheme,
    scopeSeparator: ','
  );

  @override
  AccessTokenResponse http2TokenResponse(http.Response response,
      {List<String>? requestedScopes}) {
    Map<String, dynamic> rMap = jsonDecode(response.body);

   //A bit hacky, but should work...
    return AccessTokenResponse.fromHttpResponse(
        http.Response(rMap['body'], response.statusCode),
        requestedScopes: requestedScopes);
  }
}
```

When you need to fetch the userid field, just call the getRespField method:

```dart
....
var userId = tknResp.getRespField('userid');
...
```

Hope it helps, let me know if you find any issue!

**Comment by jy-simplec** [comment]
Thank you @okrad I will definitely test it out tomorrow and let you know!

**Comment by jy-simplec** [comment]
@okrad I can confirm 2.1.0 works for both Android and iOS. Thank you! The only change needed was:

return AccessTokenResponse.fromHttpResponse(
        http.Response(rMap['body'], response.statusCode),
        requestedScopes: requestedScopes);

to

return AccessTokenResponse.fromHttpResponse(
        http.Response(jsonEncode(rMap['body']), response.statusCode),
        requestedScopes: requestedScopes);

since http.Response is expecting a string.

Now if we can get flutter_web_auth to merge my 2 PR's, and the "savedHistory" PR, I'm golden!

**Comment by okrad** [comment]
Fine, thank you for testing it out!
