### ISSUE TITLE
Custom URI Scheme Error

### ISSUE THREAD

**Issue by exemplari** [teranetsrl/oauth2_client#74]
I followed the instruction for an Android build but kept getting a 400 error for custom schema not acceptable. 

`
//Instantiate an OAuth2Client...
GoogleOAuth2Client client = GoogleOAuth2Client(
	customUriScheme: 'my.test.app' //Must correspond to the AndroidManifest's "android:scheme" attribute
	redirectUri: 'my.test.app://oauth2redirect', //Can be any URI, but the scheme part must correspond to the customeUriScheme
);
`

It turns out there is a small error in this documentation when compared to the google developers documentation.

https://developers.google.com/identity/protocols/oauth2/native-app#step1-code-verifier
`
https://accounts.google.com/o/oauth2/v2/auth?
 scope=email%20profile&
 response_type=code&
 state=security_token%3D138r5719ru3e1%26url%3Dhttps%3A%2F%2Foauth2.example.com%2Ftoken&
 redirect_uri=com.example.app%3A/oauth2redirect&
 client_id=client_id
`

Per the official android documentation , there is only one forward slash /

Changing this in the oauth2_client made my app work. 

`
//Instantiate an OAuth2Client...
GoogleOAuth2Client client = GoogleOAuth2Client(
	customUriScheme: 'my.test.app' //Must correspond to the AndroidManifest's "android:scheme" attribute
	redirectUri: 'my.test.app:/oauth2redirect', //Can be any URI, but the scheme part must correspond to the customeUriScheme
);
`

**Comment by okrad** [comment]
Hi @exemplari, thank you, I'll update the README asap!

**Comment by okrad** [comment]
README updated! (24e2097e3bb38e4528d16db9261bd4d068c2f548)
