### ISSUE TITLE
strava? getting 'bad request'

### ISSUE THREAD

**Issue by hallr-boulder** [teranetsrl/oauth2_client#77]
More of a question than a bug report. Has anyone gotten oauth_client to work with Strava via a Flutter app?

The request generated by oauth2_client sent to www.strava.com/oauth/mobile/authorize appears to be valid but  I'm consistently getting a "bad request" when webAuthClient.authenticate is called

I believe that I've set up a custom client and modified AndroidManifest.xml correctly. I'm using the same clientID and secret that work correctly in a Web app. I've played with various forms of the redirectUri without luck.

I'm looking for suggestions and ideas.  Thanks in advance!!

**Comment by hallr-boulder** [comment]
Got things working (Flutter/Android) with Strava so leaving notes for the next person.

1. In the intent-filter in AndroidManifest.xml I used:  <data android:scheme="myapp://localhost" />
2. In a custom Auth2Client extending OAuth2Client:
          authorizeUrl:  'https://www.strava.com/oauth/mobile/authorize', 
          tokenUrl: 'https://www.strava.com/api/v3/oauth/token?client_id=myClientID&client_secret=mySecret', 
          customUriScheme: 'myapp',
          redirectUri: 'myapp://localhost',

**Comment by okrad** [comment]
Thank you @hallr-boulder, hope it will be useful to someone else!
