### ISSUE TITLE
Suggestion: Make use of releases on GitHub

### ISSUE THREAD

**Issue by MarkOSullivan94** [teranetsrl/oauth2_client#79]
First off, thanks to everyone who has contributed towards this package! 😄 

It'd be great if the GitHub [releases](https://github.com/teranetsrl/oauth2_client/releases) section could be updated with each new release published.

**Comment by okrad** [comment]
Thank you @MarkOSullivan94 for the suggestion, I'll try to keep the releases section updated from now on!
