### ISSUE TITLE
Flutter Web Keycloak login not redirect

### ISSUE THREAD

**Issue by ireshmw** [teranetsrl/oauth2_client#85]
Hello! 
I'm trying to authenticate my Flutter Web app with Keycloak.  When I request a token new tab will open and show me the keycloak login page and after authuntication success, the pop tab will not close and redirect the URL open on that poped tab instead of closing it.

is there any way to get a sample code for flutter web authenticates?

Below is the code which I use. 

`
```
class KeycloakOAuth2Client extends OAuth2Client {
  KeycloakOAuth2Client(
      {required String redirectUri, required  String customUriScheme})
      : super(
      authorizeUrl:
      'http://localhost:8080/auth/realms/spring-gateway-realm/protocol/openid-connect/auth',
      tokenUrl:
      'http://localhost:8080/auth/realms/spring-gateway-realm/protocol/openid-connect/token',
      revokeUrl : 'http://localhost:8080/auth/realms/spring-gateway-realm/protocol/openid-connect/logout',
      redirectUri: redirectUri,
      customUriScheme: customUriScheme) {
    this.accessTokenRequestHeaders = {'Accept': 'application/json'};
  }
}
```

> `

Token requesting part 

```
          KeycloakOAuth2Client client = KeycloakOAuth2Client(
              customUriScheme: 'com.iresh',
              redirectUri: '${Uri.base}');

          OAuth2Helper helper = OAuth2Helper(client,
              grantType: OAuth2Helper.AUTHORIZATION_CODE, clientId: clientId);
          var tknResp = await helper.getToken();

```

**Comment by ireshmw** [comment]
Is anyone having this issue?

**Comment by okrad** [comment]
Hi @ireshmw, 
from your example it looks like you are using a custom scheme, but on the web platform you should use http(s) urls for the redirectUri, or else the browser won't be able to "intercept" it.

Hope it helps!

**Comment by ireshmw** [comment]
Hello @okrad 
Yes I'm working with localhost, is there any way to redirect without 'HTTPS', as I mentioned the redirection works, but it won't close the pop-up tab, instead redirected URL open in the same pop-up tab.

**Comment by okrad** [comment]
Are you still using the "com.iresh" scheme or are you using an http url?

Did you follow the instructions for the web platform in the README?

Basically, the redirect uri should point to a page in your web application with a script like this:

```javascript
window.onload = function() {
	const urlParams = new URLSearchParams(window.location.search);
	const code = urlParams.get('code');
	if(code) {
		window.opener.postMessage(window.location.href, _url_of_the_opener_window_);
	}
}
```
This way, when the server redirects the page will intercept the "code" parameter and send a postMessage to the window from which the authorization request originated (i.e. your flutter app).

**Comment by semajed** [comment]
@okrad  - I'm having a similar challenge and I am using https for custom scheme. Per your last comment, It looks like it is searching specifically for "code" in the urlParams of the responded URL. I'm using a 3rd party API and this is what I'm expecting to see come back:

> For example, if your Redirect URI is configured as https://myawesomeapp.com, upon the user authorizing your application, they would be redirected to https://myawesomeapp.com/#**access_token**=8bc63e42-1105-11e8-b642-0ed5f89f718b. This access token can then be used to authenticate through the API.

So it isn't returning "code" in the response urLParams. Will this be an issue?

**Comment by okrad** [comment]
Hi @semajed, the Authorization Code flow is a 2 step process: in the first step the server must return a "code" parameter that must be exchanged for an authorization token in the second step.

It looks like the API you are using requires a single step authorization flow, such as the "Client Credentials" flow. 
If this is the case, you should explicitly set the CLIENT_CREDENTIALS flow while instantiating the OAuthHelper, for example:
```dart
OAuth2Client client = OAuth2Client(...);

OAuth2Helper helper = OAuth2Helper(client,
   grantType: OAuth2Helper.CLIENT_CREDENTIALS, 
   clientId: 'MY_CLIENT_ID',
   clientSecret: 'MY_CLIENT_SECRET');

...
```

**Comment by semajed** [comment]
Oh excellent point, thanks for clarifying. In my case the 3rd party api asks for implicit grant flow. Thanks again for clarifying!
