### ISSUE TITLE
Exception thrown when scope not present in AccessTokenResponse.

### ISSUE THREAD

**Issue by jonathanjuursema** [teranetsrl/oauth2_client#9]
Hey! 

We've just started with implementing OAuth2 into our app using this package, thanks for building it!

I've found an issue of which I'm unsure if our own OAuth2 IDP is out of spec, or if it's just a small bug. Hope you can advise me on this. We are using the latest version.

When authenticating against our own OAuth2 IDP, when we're redirected back to the app, we encountered the following exception:

```
E/flutter (19580): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'isNotEmpty' was called on null.
E/flutter (19580): Receiver: null
E/flutter (19580): Tried calling: isNotEmpty
E/flutter (19580): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (19580): #1      TokenStorage.getScopeKey (package:oauth2_client/src/token_storage.dart:72:15)
E/flutter (19580): #2      TokenStorage.insertToken (package:oauth2_client/src/token_storage.dart:40:29)
E/flutter (19580): <asynchronous suspension>
E/flutter (19580): #3      TokenStorage.addToken (package:oauth2_client/src/token_storage.dart:34:37)
E/flutter (19580): #4      OAuth2Helper.fetchToken (package:oauth2_client/oauth2_helper.dart:91:26)
E/flutter (19580): <asynchronous suspension>
E/flutter (19580): #5      OAuth2Helper.getToken (package:oauth2_client/oauth2_helper.dart:66:23)
E/flutter (19580): <asynchronous suspension>
E/flutter (19580): #6      OAuth2Helper.get (package:oauth2_client/oauth2_helper.dart:164:41)
E/flutter (19580): #7      requestApiCallResult (package:ankev928/shared/api_call.dart:22:43)
E/flutter (19580): #8      _LoginHandlerState.login (package:ankev928/pages/login.dart:52:43)
E/flutter (19580): #9      _LoginHandlerState.initState.<anonymous closure> (package:ankev928/pages/login.dart:26:57)
E/flutter (19580): #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
E/flutter (19580): #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
E/flutter (19580): #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
E/flutter (19580): #13     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (19580): #14     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (19580): #15     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (19580): #16     _invoke (dart:ui/hooks.dart:261:10)
E/flutter (19580): #17     _drawFrame (dart:ui/hooks.dart:219:3)
E/flutter (19580):
```

In `token_storage.dart` I placed a breakpoint on the contents of `tknResp`, and found that the `scope` is `null`:

![image](https://user-images.githubusercontent.com/1134192/81503809-03140b00-92e6-11ea-9297-c74fdbf945d1.png)

I'm thinking our OAuth2 IDP is not returning any scope since we are not using scopes within our server application. We're initialising the OAuth2 client with the scopes: `['*']`.

I am able to work around the issue by changing `token_storage.dart` as follows:

```
Future<void> addToken(AccessTokenResponse tknResp) async {
    tknResp.scope = ['*'];
    Map<String, Map> tokens = await insertToken(tknResp);
    await storage.write(key, jsonEncode(tokens));
}
```

So the question is, is our IDP out of spec (and should it return scope `*` when we're not explicitly working with scopes), or should the package just assume that if no scope is returned, the default is `*`? I'm not familiar enough with the OAuth2 spec to answer this question, but since we haven't run into this issue with an iOS app someone else is developing on our IDP, I've went ahead and opened an issue here.

Looking forward to a reply. :) Thanks!

**Comment by okrad** [comment]
Hi @jonathanjuursema, the specs state that the "scope" parameter in the server response is _"OPTIONAL, if identical to the scope requested by the client"_, so I guess your IDP is ok.

Up until now the scope parameter was indeed considered mandatory by the library, but the just released 1.2.4 version corrects this (mis)behaviour. Can you check it out?

**Comment by jonathanjuursema** [comment]
Hey @okrad, thanks so much for the quick reply. I'll try to check it out tomorrow and post back!

**Comment by jonathanjuursema** [comment]
Hey @okrad, this did the trick, many thanks!
