### ISSUE TITLE
Version 2.2.3 was not bumped to 2.2.3

### ISSUE THREAD

**Issue by benjaminhorner** [teranetsrl/oauth2_client#98]
Just a little note: it is not possible to install version 2.2.3 with the command `flutter pub add oauth2_client` because the version number was not bumped.
Here is the [PR](https://github.com/teranetsrl/oauth2_client/pull/97).

**Comment by AndrewStickler** [comment]
I would very much like 2.2.3, so is there any chance  of this being published soon please?

**Comment by okrad** [comment]
Hi, sorry for the delay, I just published v 2.2.4!

**Comment by AndrewStickler** [comment]
Hi @okrad - version 2.2.4 has broken oauth's authorize request - see https://github.com/teranetsrl/oauth2_client/issues/100.
